kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: mjhea0/spark-hadoop:2.2.1
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          # resources:
          #   requests:
          #     cpu: 100m
          resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
            limits:
              memory: "1000Mi"
              cpu: "500m" 
          livenessProbe:
            exec:
              command:
                - /bin/bash
            initialDelaySeconds: 10
            periodSeconds: 25
          readinessProbe:
            exec:
              command:
                - /bin/bash
            initialDelaySeconds: 5
            periodSeconds: 10
